# Generated by Django 4.2.5 on 2023-09-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
