# Generated by Django 4.2.5 on 2023-09-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidplayer', '0002_videos_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
