# Generated by Django 4.2.5 on 2023-09-29 00:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidplayer', '0003_videos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
