# Generated by Django 3.2.9 on 2023-10-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidplayer', '0005_transcription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='video',
            new_name='file',
        ),
    ]
