# Generated by Django 4.2.5 on 2023-10-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidplayer', '0006_rename_video_videos_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Transcription',
        ),
    ]
