# Generated by Django 4.2.5 on 2023-10-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidplayer', '0007_videos_text_delete_transcription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='text',
            new_name='transcription',
        ),
    ]
